version: "3.3"

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/${POSTGRES_PORT}; do sleep 1; done; uvicorn app.main:app --host 0.0.0.0'
    ports:
      - 8008:8000
    env_file:
      # see .env_example
      - .env
    environment:
      # from .env
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      # database folder created in project root
      - ./data/postgres:/var/lib/postgresql/data
    expose:
      # from .env
      - ${POSTGRES_PORT}
    environment:
      # from .env
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}

volumes:
  data: {}
